name 'nodejs'
maintainer 'Gontar Konstantin'
maintainer_email 'gontarkonstantin@gmail.com'
license 'all_rights'
description 'Installs/Configures nodejs'
long_description 'Installs/Configures nodejs'
version '0.1.0'
